version: 2
jobs:
  build:
    working_directory: ~/mindsharp-news
    docker:
      - image: rayriffy/php:alpine-phplint
    steps:
      - checkout
      - run:
          name: Test Files
          command: |
            cd ~/phplint
            ./vendor/bin/parallel-lint ~/mindsharp-news/*
  deploy:
    machine:
        enabled: true
    working_directory: ~/mindsharp-news
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c7:29:52:e0:f0:33:ca:91:1b:30:3a:96:1f:34:a7:fd"
      - run:
          name: Deploy to Server
          command: |
            ssh -i ~/.ssh/id_rsa_c72952e0f033ca911b303a961f34a7fd circleci@deploy.rayriffy.com 'cd ~/landing/mindsharp-news && git pull'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master